steps:

  - command: |-
      echo "~~~ pip install"
      echo 'odus' | sudo -S rm -rf /tmp/pip_build_root/*
      echo 'odus' | sudo -S pip install -r requirements.txt

      echo "~~~ test app"
      python -m unittest discover tests

    label: application test

  - command: |-
      echo "~~~ pip install"
      echo 'odus' | sudo -S rm -rf /tmp/pip_build_root/*
      echo 'odus' | sudo -S pip install -r requirements.txt

      echo "~~~ building dist"
      rm -rf dist/*
      python setup.py sdist

      echo "~~~ testing dist"
      VERSION=$(cat binlogexplorer/version)
      echo 'odus' | sudo -S pip uninstall mysql-binlog-explorer -y || true
      echo 'odus' | sudo -S pip install dist/mysql-binlog-explorer-\${VERSION}.tar.gz --no-cache-dir
      mysql-binlog-explorer -h

    label: package distribution test

  - wait

  - command: |-
      echo "~~~ pip install"
      echo 'odus' | sudo -S rm -rf /tmp/pip_build_root/*
      echo 'odus' | sudo -S pip install -r requirements_ci.txt

      echo "~~~ cleaning"
      rm -rf dist

      echo "~~~ publishing"
      ./publish.sh

    label: publish
    branches: master
    concurrency: 1
    concurrency_group: 'mysql-binlog-explorer-deploy'
